config/routes.rb
Rails.application.routes.draw do
  devise_for :volenters, controllers: { registrations: 'volenters/registrations' } 
  resources :associates
  resources :volenters
  resources :centers

  root 'welcome#index'

  get 'select_center' => 'welcome#select'

  get 'search_center', to: 'welcome#search'

  get 'verification' ,to: 'associates#verify'

  post 'verification2' ,to: 'associates#verify2'

  get 'associate/listing', to: 'associates#listing'

  get '/populate_state_from_selected_country' => 'centers#populate_state_from_selected_country'

  get '/populate_district_from_selected_state' => 'centers#populate_district_from_selected_state'

  get '/populate_sub_district_from_selected_district' => 'centers#populate_sub_district_from_selected_district'

  get '/populate_city_from_selected_sub_district' => 'centers#populate_city_from_selected_sub_district'

end

app/models/volenter.rb
class Volenter < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :center
  has_many :associates
end

app/controllers/volenters/confirmations_controller.rb
# frozen_string_literal: true

class Volenters::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/volenters/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Volenters::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/volenters/passwords_controller.rb
# frozen_string_literal: true

class Volenters::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/volenters/registrations_controller.rb
# frozen_string_literal: true

class Volenters::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  after_action :try,only:[:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    
    super
  end

  def try
    center_id = params[:volenter][:center_id]
    center = Center.find(center_id)
    center.volenter_id = current_volenter.id
    center.no_of_volenters = center.volenter.count
    center.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:age,:address,:phone_no,:adhaar_no,:center_id,:gender])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/volenters/sessions_controller.rb
# frozen_string_literal: true

class Volenters::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/volenters/unlocks_controller.rb
# frozen_string_literal: true

class Volenters::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/volenters_controller.rb
class VolentersController < ApplicationController
  before_action :set_volenter, only: [:show, :edit, :update, :destroy]

  # GET /volenters
  # GET /volenters.json
  def index
    if volenter_signed_in? && current_volenter.is_super_admin? 
      @volenters = Volenter.all 
    elsif volenter_signed_in?
      @volenters = Volenter.where(center_id: current_volenter.center_id)
    else
      @volenters =  Volenter.all
    end
  end

  # GET /volenters/1
  # GET /volenters/1.json
  def show
  end

  # GET /volenters/new
  def new
    @volenter = Volenter.new
  end

  # GET /volenters/1/edit
  def edit
  end

  # POST /volenters
  # POST /volenters.json
  def create
    respond_to do |format|
      if @volenter.save
        format.html { redirect_to @volenter, notice: 'Volenter was successfully created.' }
        format.json { render :show, status: :created, location: @volenter }
      else
        format.html { render :new }
        format.json { render json: @volenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volenters/1
  # PATCH/PUT /volenters/1.json
  def update
    respond_to do |format|
      if @volenter.update(volenter_params)
        format.html { redirect_to @volenter, notice: 'Volenter was successfully updated.' }
        format.json { render :show, status: :ok, location: @volenter }
      else
        format.html { render :edit }
        format.json { render json: @volenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volenters/1
  # DELETE /volenters/1.json
  def destroy
    @volenter.destroy
    respond_to do |format|
      format.html { redirect_to volenters_url, notice: 'Volenter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volenter
      @volenter = Volenter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volenter_params
      params.require(:volenter).permit(:name, :age, :gender, :address, :phone_no, :adhaar_no, :center_id)
    end
end

app/helpers/volenters_helper.rb
module VolentersHelper
end

app/views/volenters/_form.html.erb
<%= simple_form_for(@volenter) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :gender %>
    <%= f.input :address %>
    <%= f.input :phone_no %>
    <%= f.input :adhaar_no %>
    <%= f.association :center %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/volenters/edit.html.erb
<h1>Editing Volenter</h1>

<%= render 'form' %>

<%= link_to 'Show', @volenter %> |
<%= link_to 'Back', volenters_path %>

app/views/volenters/index.html.erb
<%= render 'welcome/nav' %>
<div class="container" style='margin-top:50px'>
<div class="row">
<div class="col-xs-12 results" >
 <h3>All Volenters</h3>
 <div class="container">
<div class="col-md-10">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Address</th>
            <th>Phone no</th>
            <th>Adhaar no</th>
            <th>Center</th>
            <th colspan="3">Action</th>
          </tr>
        </thead>

        <tbody>
          <% @volenters.each do |volenter| %>
            <tr>
              <td><%= link_to volenter.name,volenter %></td>
              <td><%= volenter.age %></td>
              <td><%= volenter.gender %></td>
              <td><%= volenter.address %></td>
              <td><%= volenter.phone_no %></td>
              <td><%= volenter.adhaar_no %></td>
              <% if volenter.center.present?
                  @name = Center.find(volenter.center)
                  @center_name = @name.name
                end
              %>
              <td><%= @center_name %></td>
              <td><%= link_to 'View', volenter %></td>
              <td><%= link_to 'Edit', edit_volenter_path(volenter) %></td>
              <td><%= link_to 'Delete', volenter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
    </div>
  </div>  

app/views/volenters/new.html.erb
<h1>New Volenter</h1>

<%= render 'form' %>

<%= link_to 'Back', volenters_path %>

app/views/volenters/show.html.erb
<%= render :partial => '/welcome/nav' %>

<div class="container" style='margin-top:50px'>
<h2>Profile info</h2>
  <div class="col-md-10">
    <p id="notice"><%= notice %></p>

    <%
        center_name = Center.find(@volenter.center)
        @center_name = center_name.name
    %>

    <p>
      <strong>Name:</strong>
      <%= @volenter.name %>
    </p>

    <p>
      <strong>Age:</strong>
      <%= @volenter.age %>
    </p>

    <p>
      <strong>Gender:</strong>
      <%= @volenter.gender %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @volenter.address %>
    </p>

    <p>
      <strong>Phone no:</strong>
      <%= @volenter.phone_no %>
    </p>

    <p>
      <strong>Adhaar no:</strong>
      <%= @volenter.adhaar_no %>
    </p>

    <p>
      <strong>Center:</strong>
      <%= @center_name %>
    </p>

    <%= link_to 'Edit', edit_volenter_path(@volenter) %> |
    <%= link_to 'Back', volenters_path %>
    </div>
  </div>      