config/routes.rb
Rails.application.routes.draw do
  devise_for :volenters, controllers: { registrations: 'volenters/registrations' } 
  resources :associates
  resources :volenters
  resources :centers

  root 'welcome#index'

  get 'select_center' => 'welcome#select'

  get 'search_center', to: 'welcome#search'

  get 'verification' ,to: 'associates#verify'

  post 'verification2' ,to: 'associates#verify2'

  get 'associate/listing', to: 'associates#listing'

  get '/populate_state_from_selected_country' => 'centers#populate_state_from_selected_country'

  get '/populate_district_from_selected_state' => 'centers#populate_district_from_selected_state'

  get '/populate_sub_district_from_selected_district' => 'centers#populate_sub_district_from_selected_district'

  get '/populate_city_from_selected_sub_district' => 'centers#populate_city_from_selected_sub_district'

end

app/models/center.rb
class Center < ActiveRecord::Base
  belongs_to :country
  belongs_to :state
  belongs_to :district
  belongs_to :sub_district
  belongs_to :town_village
  has_many :volenter
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  before_action :set_center, only: [:show, :edit, :update, :destroy]
  # before_action :set_names, only: [:index, :show]

  # GET /centers
  # GET /centers.json
  def index
    @centers = Center.all
  end



def populate_state_from_selected_country 
    state_arr = []
    if params['country_id'].present?
        country_id = params[:country_id]
        @states = State.where(country_id: country_id)
        @states.each do |state|
          state_arr.push(state) 
        end  
    end
    # p mm_details_arr
    flash.now[:danger] = 'No center here' 
    #render partial: 'welcome/middle_layer'
    render json: state_arr
end

def populate_district_from_selected_state 
  district_arr = []
  if params['state_id'].present?
      state_name = params[:state_id]
      state_id = State.where(name: state_name)
      @districts = District.where(state_id: state_id)
      @districts.each do |district|
        district_arr.push(district) 
      end  
  end
  # p mm_details_arr
  render json: district_arr
end

def populate_sub_district_from_selected_district 
  sub_district_arr = []
  if params['district_id'].present?
      district_name = params[:district_id]
      district_id = District.where(name: district_name)
      @sub_districts = SubDistrict.where(district_id: district_id)
      @sub_districts.each do |sub_district|
        sub_district_arr.push(sub_district) 
      end  
  end
  # p mm_details_arr
  render json: sub_district_arr
end

def populate_city_from_selected_sub_district 
  city_arr = []
  if params['city_id'].present?
      city_name = params[:city_id]
      city_id = SubDistrict.where(name: city_name)
      @cities = TownVillage.where(sub_district_id: city_id)
      @cities.each do |district|
        city_arr.push(district) 
      end  
  end
  # p mm_details_arr
  render json: city_arr
end

  # GET /centers/1
  # GET /centers/1.json
  def show
    @centers = Center.all
  end

  # GET /centers/new
  def new
    @center = Center.new
  end

  # GET /centers/1/edit
  def edit
  end

  # POST /centers
  # POST /centers.json
  def create
    @center = Center.new(center_params)

    respond_to do |format|
      if @center.save
        format.html { redirect_to @center, notice: 'Center was successfully created.' }
        format.json { render :show, status: :created, location: @center }
      else
        format.html { render :new }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centers/1
  # PATCH/PUT /centers/1.json
  def update
    respond_to do |format|
      if @center.update(center_params)
        format.html { redirect_to @center, notice: 'Center was successfully updated.' }
        format.json { render :show, status: :ok, location: @center }
      else
        format.html { render :edit }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centers/1
  # DELETE /centers/1.json
  def destroy
    @center.destroy
    respond_to do |format|
      format.html { redirect_to centers_url, notice: 'Center was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_center
      @center = Center.find(params[:id])
    end

    def set_names
      @centers = Center.all
      @centers.each do |center|
      
        country_name = Country.find(center.country_id)
        @center_country = country_name.name
  
        state_name = State.find(center.state_id)
        @center_state = state_name.name
  
        district_name = District.find(center.district_id)
        @center_district = district_name.name
  
        sub_district_name = SubDistrict.find(center.sub_district_id)
        @center_sub_district = sub_district_name.name
  
        city_name = TownVillage.find(center.town_village_id)
        @center_city = city_name.name
      end 
    end   

    # Never trust parameters from the scary internet, only allow the white list through.
    def center_params
      params.require(:center).permit(:name, :address, :no_of_volenters, :country_id, :state_id, :district_id, :sub_district_id, :town_village_id)
    end
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/views/centers/_form.html.erb
<div class="container">
  <div class="col-md-10">
    <div class="form-area">  
      <%= simple_form_for(@center,class: 'form-inline') do |f|  %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs ">
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.association :country %>
          <%= f.association :state %>
          <%= f.association :district %>
          <%= f.association :sub_district %>
          <%= f.association :town_village %>
        </div>

        <div class="form-actions">
          <%= f.button :submit,'Save',class: 'btn btn-primary' %>
        </div>
      <% end %>
</div></div>      

app/views/centers/edit.html.erb
<h1>Editing Center</h1>

<%= render 'form' %>

<%= link_to 'Show', @center %> |
<%= link_to 'Back', centers_path %>

app/views/centers/index.html.erb
<div class="container">
  <div class="col-md-10">
      <p id="notice"><%= notice %></p>

      <h1>Listing Centers</h1>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th>No of volenters</th>
            <th>Country</th>
            <th>State</th>
            <th>District</th>
            <th>Sub district</th>
            <th>Town village</th>
            <th colspan="3" style="text-align:center">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @centers.each do |center| %>
            <%
            country_name = Country.find(center.country_id)
            @center_country = country_name.name
      
            state_name = State.find(center.state_id)
            @center_state = state_name.name
      
            district_name = District.find(center.district_id)
            @center_district = district_name.name
      
            sub_district_name = SubDistrict.find(center.sub_district_id)
            @center_sub_district = sub_district_name.name
      
            city_name = TownVillage.find(center.town_village_id)
            @center_city = city_name.name
            %> 
            <tr>
              <td><%= center.name %></td>
              <td><%= center.address %></td>
              <td><%= center.no_of_volenters %></td>
              <td><%= @center_country %></td>
              <td><%= @center_state %></td>
              <td><%= @center_district %></td>
              <td><%= @center_sub_district %></td>
              <td><%= @center_city %></td>
              <td><%= link_to 'Show', center %></td>
              <td><%= link_to 'Edit', edit_center_path(center) %></td>
              <td><%= link_to 'Destroy', center, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Center', new_center_path %>
  </div>
</div>      

app/views/centers/new.html.erb
<h1>New Center</h1>

<%= render 'form' %>

<%= link_to 'Back', centers_path %>

app/views/centers/show.html.erb
<div class="container">
  <div class="col-md-10">
      <p id="notice"><%= notice %></p>
     
        <%
        center = @center 

        country_name = Country.find(center.country_id)
        @center_country = country_name.name
  
        state_name = State.find(center.state_id)
        @center_state = state_name.name
  
        district_name = District.find(center.district_id)
        @center_district = district_name.name
  
        sub_district_name = SubDistrict.find(center.sub_district_id)
        @center_sub_district = sub_district_name.name
  
        city_name = TownVillage.find(center.town_village_id)
        @center_city = city_name.name
        %> 

      <p>
        <strong>Name:</strong>
        <%= @center.name %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @center.address %>
      </p>

      <p>
        <strong>No of volenters:</strong>
        <%= @center.no_of_volenters %>
      </p>

      <p>
        <strong>Country:</strong>
        <%= @center_country %>
      </p>

      <p>
        <strong>State:</strong>
        <%= @center_state %>
      </p>

      <p>
        <strong>District:</strong>
        <%= @center_district %>
      </p>

      <p>
        <strong>Sub district:</strong>
        <%= @center_sub_district %>
      </p>

      <p>
        <strong>Town village:</strong>
        <%= @center_city %>
      </p>

      <%= link_to 'Edit', edit_center_path(@center) %> |
      <%= link_to 'Back', centers_path %>
  </div>
</div>      