config/routes.rb
Rails.application.routes.draw do
  devise_for :volenters, controllers: { registrations: 'volenters/registrations' } 
  resources :associates
  resources :volenters
  resources :centers

  root 'welcome#index'

  get 'select_center' => 'welcome#select'

  get 'search_center', to: 'welcome#search'

  get 'verification' ,to: 'associates#verify'

  post 'verification2' ,to: 'associates#verify2'

  get 'associate/listing', to: 'associates#listing'

  get '/populate_state_from_selected_country' => 'centers#populate_state_from_selected_country'

  get '/populate_district_from_selected_state' => 'centers#populate_district_from_selected_state'

  get '/populate_sub_district_from_selected_district' => 'centers#populate_sub_district_from_selected_district'

  get '/populate_city_from_selected_sub_district' => 'centers#populate_city_from_selected_sub_district'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    # before_action :set_names
    
    def index
        @center = Center.all
        @countries = Country.all
        @state = State.all
        @district = District.all
        @sub_district = SubDistrict.all
        @city = TownVillage.all      
    end   


    def select
        if params[:country].blank? 
            flash.now[:danger] = 'Please enter name to search'
        else
            country_id = (params[:country])
            c = Country.find(country_id)
 
            state_name = params[:state] 
            s = State.where(name: state_name).pluck(:id) if state_name.present?       

            district_name = params[:district]
            d = District.where(name: district_name).pluck(:id) if district_name.present?

            sub_district_name = params[:sub_district]
            sd = SubDistrict.where(name: sub_district_name).pluck(:id) if sub_district_name.present?

            city_name = params[:city]
            t = SubDistrict.where(name: city_name).pluck(:id) if city_name.present?
           
            if country_id.present? && state_name.blank? && district_name.blank? && sub_district_name.blank? && city_name.blank?
                @center = Center.where(country_id: c) 
            elsif country_id.present? && state_name.present? && district_name.blank? && sub_district_name.blank? && city_name.blank?
                @center = Center.where(country_id: c,state_id: s)
            elsif country_id.present? && state_name.present? && district_name.present? && sub_district_name.blank? && city_name.blank?
                @center = Center.where(country_id: c,state_id: s,district_id: d)
            elsif country_id.present? && state_name.present? && district_name.present? && sub_district_name.present? && city_name.blank?
                @center = Center.where(country_id: c,state_id: s,district_id: d,sub_district_id: sd)
            elsif country_id.present? && state_name.present? && district_name.present? && sub_district_name.present? && city_name.present?
                @center = Center.where(country_id: c,state_id: s,district_id: d,sub_district_id: sd,town_village_id: t)                
            end
            flash.now[:danger] = 'We don\'t have center here.We are working to get here!!.Thank you.' if @center.blank?         
            flash.now[:info] = 'There are following centers in this area.' if @center.present? 
        end 
        render partial: 'welcome/middle_layer'
    end

    def search
        if params[:name].blank? 
            flash.now[:danger] = 'Please enter name to search'
        else  
           name = (params[:name])
           c_id = Country.where("name LIKE ?", "%"+name+"%").pluck(:id);
           s_id = State.where("name LIKE ?", "%"+name+"%").pluck(:id); 
           d_id = District.where("name LIKE ?", "%"+name+"%").pluck(:id);
           sd_id = SubDistrict.where("name LIKE ?", "%"+name+"%").pluck(:id);
           t_id = TownVillage.where("name LIKE ?", "%"+name+"%").pluck(:id);
           @center = Center.where("name LIKE ? OR country_id IN (?) OR state_id IN (?) OR district_id IN (?) OR sub_district_id IN (?)  OR town_village_id IN (?) ", "%"+name+"%",c_id,s_id,d_id,sd_id,t_id)
               #@c_id = Country.where("name LIKE ?", "%"+name+"%").pluck(:id).first;
                # if @c_id.blank?
                #     @s_id = State.where("name LIKE ?", "%"+name+"%").pluck(:id).first;    
                #       if @s_id.blank?

                #       else
                #         @center = Center.where("state_id = ?", @s_id)
                #       end 
                # else
                #     @center = Center.where("country_id = ?", @c_id)
                # end            
                flash.now[:danger] = 'We don\'t have center here.We are working to get here!!.Thank you.' if @center.blank?               
                flash.now[:info] = 'There are following centers in this area.' if @center.present? 
        end
            render partial: 'welcome/middle_layer'
     end  


    def set_names
        @centers = Center.all
        @centers.each do |center|
        

        end 
    end   
    
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_middle_layer.html.erb
<% if params[:action] == 'search' || params[:action] == 'select' %>
  <div class='results-block container' style='text-align:center'>
      <br>
        <%= bootstrap_flash %>
    </div>
<% end %> 
<% if @center.present? %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 results" >
      <h3>List of All Centers:</h3>
      <div class="container">
  <div class="col-md-10">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th>No of volenters</th>
            <th>Country</th>
            <th>State</th>
            <th>District</th>
            <th>Sub district</th>
            <th>Town village</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @center.each do |center| %>
            <%
            country_name = Country.find(center.country_id)
            @center_country = country_name.name
      
            state_name = State.find(center.state_id)
            @center_state = state_name.name
      
            district_name = District.find(center.district_id)
            @center_district = district_name.name
      
            sub_district_name = SubDistrict.find(center.sub_district_id)
            @center_sub_district = sub_district_name.name
      
            city_name = TownVillage.find(center.town_village_id)
            @center_city = city_name.name
            %>
            <tr>
              <td><%= link_to center.name, center %></td>
              <td><%= center.address %></td>
              <td><%= center.volenter.count %></td>
              <td><%= @center_country %></td>
              <td><%= @center_state %></td>
              <td><%= @center_district %></td>
              <td><%= @center_sub_district %></td>
              <td><%= @center_city %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
    </div>
  </div>
</div>
<% else %>
  <h3 style='text-align:center '> We are working to get here soon.</h3>
<% end %> 

app/views/welcome/_nav.html.erb
<div class="navbar navbar-default navbar-fixed-top" style='opacity: 0.9'>
<div class="container-fluid">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <div class="navbar-header">
  <%= link_to "Saryodya",  root_path, class: 'navbar-brand'  %>
  </div>  
  <div class="navbar-collapse collapse navbar-responsive-collapse" style='float:right'>
    <ul class="nav navbar-nav">
      <% if  volenter_signed_in? && current_volenter.is_admin? %>
        <li><%= link_to "Create Center", new_center_path  %></li>
      <% end %>  
      <li><%= link_to "Bussiness Listing", associate_listing_path  %></li>
      <li><%= link_to "Volenters", volenters_path  %></li>
      <div class="dropdown">
      <button class="dropbtn">Account</button>
      <div class="dropdown-content">
      <% if volenter_signed_in? %>
        <li><%= link_to "My Profile", volenter_path(:id => current_volenter.id) %></li>
        <li><%= link_to "Sign out",  destroy_volenter_session_path, method: :delete%></li>
      <% else %>
        <li><%= link_to "Sign in",  new_volenter_registration_path %></li>
        <li><%= link_to "Log in",  new_volenter_session_path %></li>
      <% end %>
      </div>
    </div>  
    </ul>

  </div>
</div>
</div>

<span style='position:relative;top:60px;text-align:center' id='main-flash' >
<%= bootstrap_flash %>
</span>

<div class="container">
<div class="row">
  <div class="col-lg-12">
    <%= yield %>
  </div>
</div><!--/row-->


</div> <!-- /container -->

app/views/welcome/_search.html.erb
<div class='form search' >   
<div class="form-group row">
<%= form_tag 'search_center', remote: true, method: :get, id: 'search-form' do %>
    <div class="col-sm-10">
        
    <%= text_field_tag :name, params[:name], placeholder: 'Search Country / State /etc name', 
    autofocus: true, class: 'form-control search-box input-lg' %>
    </div>
     
     <div class="col-sm-2" >
     <%= button_tag(type: :submit, class: 'btn btn-lg btn-primary') do %>
        <i class='fa fa-search'></i> Search
     <% end  %>  

     </div>  
 <% end %>
</div> 
</div>

app/views/welcome/_select.html.erb
<div class='form'>   
<div class="form-group row" style='margin-left:20px' >
 <%= form_tag 'select_center',remote: true, method: :get, id: 'select-form',
    class: 'form-inline' do  %>
    <div class="col-sm-2" style="width:20%">
        <%= select_tag "country", options_from_collection_for_select(@countries, "id", "name"),class:'form-control' ,include_blank: 'Country'%> 
    </div>
    <div class="col-sm-2" style="width:15%">
        <%= select_tag "state", options_from_collection_for_select(@state, "id", "name"),class:'form-control' ,include_blank: 'State'%> 
     </div>
     <div class="col-sm-2" style="width:18%">
        <%= select_tag "district", options_from_collection_for_select(@district, "id", "name"),class:'form-control' ,include_blank: 'District'%> 
     </div>
     <div class="col-sm-2" style="width:22%">
        <%= select_tag "sub_district", options_from_collection_for_select(@sub_district, "id", "name"),class:'form-control' ,include_blank: 'Sub_District'%> 
     </div>
     <div class="col-sm-2" style="width:20%">
     <%= select_tag "city", options_from_collection_for_select(@city, "id", "name"),class:'form-control' ,include_blank: 'City'%> 
     </div>
     
     <div class="col-sm-2" style="position:absolute;left:85%">
     <%= button_tag(type: :submit, class: 'btn btn-md btn-primary') do %>
        <i class='fa fa-search'></i> Search
     <% end  %>  
     </div>  
 <% end %>
</div> 
</div>

<script>
$(document).ready(function(){
    $("#country").change(function(){
      let v = $("#country").val();
      populateState(v);

      function populateState(countryID) {
        $.ajax({
            url: `/populate_state_from_selected_country`,
            type: 'GET',
            dataType: 'json',
            contentType: 'application/json',
            data: { country_id: countryID },
            success: data => {
                 console.log(data);
                const $stateDropdown = document.getElementById('state');
                const $districtDropdown = document.getElementById('district');
                const $subDistrictDropdown = document.getElementById('sub_district');
                const $cityDropdown = document.getElementById('city');
                const $flash = document.getElementById('main-flash');
                $stateDropdown.innerHTML = '';
                if (data.length > 0) {
                    
                    $stateDropdown.innerHTML += '<option value="">State</option>';

                    for (const value of data) {
                      console.log(value["name"]);
                        $stateDropdown.innerHTML += `<option value="${value["name"]}">${value["name"]}</option>`;
                    }
                    $("#state").prop('disabled',false);
                    $("#district").prop('disabled',false);
                    $("#sub_district").prop('disabled',false);
                    $("#city").prop('disabled',false);
                } else {
                    $stateDropdown.innerHTML += '<option value="">State</option>';
                    $flash.innerHTML += 
                    '<div class="alert fade in alert-danger"><button type="button" class="close" data-dismiss="alert">X</button>We don\'t have center here.We are working to get here!!.Thank you</div>';
                    $("#state").prop('disabled','disabled');
                    $("#district").prop('disabled','disabled');
                    $("#sub_district").prop('disabled','disabled');
                    $("#city").prop('disabled','disabled');
                }
            }
        });
    }
    });
 });

 $("#state").change(function(){
  let v = $("#state").val();
  populateDistrict(v);
  
  function populateDistrict(stateID) {
    $.ajax({
        url: `/populate_district_from_selected_state`,
        type: 'GET',
        dataType: 'json',
        contentType: 'application/json',
        data: { state_id: stateID },
        success: data => {
             console.log(data);
            const $districtDropdown = document.getElementById('district');
            const $flash = document.getElementById('main-flash');
            $districtDropdown.innerHTML = '';
            if (data.length > 0) {
                $districtDropdown.innerHTML += '<option value="">District</option>';
                for (const value of data) {
                  console.log(value["name"]);
                    $districtDropdown.innerHTML += `<option value="${value["name"]}">${value["name"]}</option>`;
                }
                $("#district").prop('disabled',false);
                $("#sub_district").prop('disabled',false);
                $("#city").prop('disabled',false);
            } else {
                $districtDropdown.innerHTML += '<option value="">District</option>';
                $flash.innerHTML += 
                '<div class="alert fade in alert-danger"><button type="button" class="close" data-dismiss="alert">X</button>We don\'t have center here.We are working to get here!!.Thank you.</div>';
                $("#state").prop('disabled','disabled');
                $("#district").prop('disabled','disabled');
                $("#sub_district").prop('disabled','disabled');
                $("#city").prop('disabled','disabled');
            }
        }
    });
  }
});


$("#district").change(function(){
    let v = $("#district").val();
    populateSubDistrict(v);
  
    function populateSubDistrict(districtID) {
      $.ajax({
          url: `/populate_sub_district_from_selected_district`,
          type: 'GET',
          dataType: 'json',
          contentType: 'application/json',
          data: { district_id: districtID },
          success: data => {
               console.log(data);
              const $subDistrictDropdown = document.getElementById('sub_district');
              $subDistrictDropdown.innerHTML = '';
              const $flash = document.getElementById('main-flash');
              if (data.length > 0) {
                  $subDistrictDropdown.innerHTML += '<option value="">Sub-District</option>';
                  for (const value of data) {
                    console.log(value["name"]);
                      $subDistrictDropdown.innerHTML += `<option value="${value["name"]}">${value["name"]}</option>`;
                  }
                  $("#sub_district").prop('disabled',false);
                  $("#city").prop('disabled',false);
              } else {
                $subDistrictDropdown.innerHTML += '<option value="">Sub-District</option>';
                $flash.innerHTML += 
                '<div class="alert fade in alert-danger"><button type="button" class="close" data-dismiss="alert">X</button>We don\'t have center here.We are working to get here!!.Thank you</div>';
                $("#state").prop('disabled','disabled');
                $("#district").prop('disabled','disabled');
                $("#sub_district").prop('disabled','disabled');
                $("#city").prop('disabled','disabled');
              }
          }
      });
    }
  });

  $("#sub_district").change(function(){
    let v = $("#sub_district").val();
    populateCity(v);
  
    function populateCity(cityID) {
      $.ajax({
          url: `/populate_city_from_selected_sub_district`,
          type: 'GET',
          dataType: 'json',
          contentType: 'application/json',
          data: { city_id: cityID },
          success: data => {
               console.log(data);
              const $cityDropdown = document.getElementById('city');
              $cityDropdown.innerHTML = '';
              if (data.length > 0) {
                  $cityDropdown.innerHTML += '<option value="">City/Town</option>';
                  const $flash = document.getElementById('main-flash');
                  for (const value of data) {
                    console.log(value["name"]);
                      $cityDropdown.innerHTML += `<option value="${value["name"]}">${value["name"]}</option>`;
                  }
                  $("#city").prop('disabled',false);
              } else {
                $cityDropdown.innerHTML += '<option value="">City/Town</option>';
                $flash.innerHTML += 
                '<div class="alert fade in alert-danger"><button type="button" class="close" data-dismiss="alert">X</button>We don\'t have center here.We are working to get here!!.Thank you</div>';
                $("#state").prop('disabled','disabled');
                $("#district").prop('disabled','disabled');
                $("#sub_district").prop('disabled','disabled');
                $("#city").prop('disabled','disabled');
              }
          }
      });
    }
  });


</script>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Saryodya" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
  <div class="container-fluid height-full bg">
  <div class="row">
    <div class="col-xs-12">
      <%= render :partial => 'nav' %>
      <%= render :partial => 'select' %>
      <div class='or'>
        OR
      </div>
      <%= render :partial => 'search' %>   
 </div> 
</div>
</div>
<div id='results'>
   <%= render :partial => 'middle_layer' %>
   </div>   
  </body>
</html>