config/routes.rb
Rails.application.routes.draw do
  devise_for :volenters, controllers: { registrations: 'volenters/registrations' } 
  resources :associates
  resources :volenters
  resources :centers

  root 'welcome#index'

  get 'select_center' => 'welcome#select'

  get 'search_center', to: 'welcome#search'

  get 'verification' ,to: 'associates#verify'

  post 'verification2' ,to: 'associates#verify2'

  get 'associate/listing', to: 'associates#listing'

  get '/populate_state_from_selected_country' => 'centers#populate_state_from_selected_country'

  get '/populate_district_from_selected_state' => 'centers#populate_district_from_selected_state'

  get '/populate_sub_district_from_selected_district' => 'centers#populate_sub_district_from_selected_district'

  get '/populate_city_from_selected_sub_district' => 'centers#populate_city_from_selected_sub_district'

end

app/models/associate.rb
class Associate < ActiveRecord::Base
  belongs_to :payment_mode
  belongs_to :center
  belongs_to :associate_category
  belongs_to :volenter

  validates :company_name, presence: true
  validates 'authy-countries', presence: true
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
  before_action :set_associate, only: [:show, :edit, :update, :destroy]

  # GET /associates
  # GET /associates.json
  def index
    @associates = Associate.all
  end

  # GET /associates/1
  # GET /associates/1.json
  def show
  end

  # GET /associates/new
  def new
    if params[:phone_number].present?
      session[:phone_number] = params[:phone_number]
      session[:country_code] = params[:country_code]

       @response = Authy::PhoneVerification.start(
        via: params[:method],
        country_code: params[:country_code],
        phone_number: params[:phone_number]
      )
    
      if @response.ok?
         'ok'
        redirect_to  verification_path,  notice: 'Plese enter Verification code'
      elsif @response.errors.present?
         @response.errors.each do |key, message| 
          redirect_to associate_listing_path ,  alert: message
        end 
      end
    end

    if params[:associate].present?
     @state = params[:associate][:associate_type] 
     session[:state] = @state
    elsif params[:state].present?
      @state =  params[:state]
      session[:state] = @state
    else
      render :new
    end
    @associate = Associate.new
    end

    def verify
    end

    def verify2
       @response = Authy::PhoneVerification.check(
        verification_code: params[:code],
        country_code: session[:country_code],
        phone_number: session[:phone_number]
      )
      if @response.ok?
        session[:phone_number] = nil
        session[:country_code] = nil
        redirect_to controller: 'associates', action: 'new', state: session['state']
      elsif @response.errors.present?
        @response.errors.each do |key, message| 
          redirect_to verification_path ,  alert: message   
        end 
      end 

    end
  # GET /associates/1/edit
  def edit
  end

  def listing
  end 

  # POST /associates
  # POST /associates.json
  def create
    @associate = Associate.new(associate_params)

    respond_to do |format|
      if @associate.save
        format.html { redirect_to @associate, notice: 'Associate was successfully created.' }
        format.json { render :show, status: :created, location: @associate }
      else
        format.html { render :new }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associates/1
  # PATCH/PUT /associates/1.json
  def update
    respond_to do |format|
      if @associate.update(associate_params)
        format.html { redirect_to @associate, notice: 'Associate was successfully updated.' }
        format.json { render :show, status: :ok, location: @associate }
      else
        format.html { render :edit }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associates/1
  # DELETE /associates/1.json
  def destroy
    @associate.destroy
    respond_to do |format|
      format.html { redirect_to associates_url, notice: 'Associate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associate
      @associate = Associate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def associate_params
      params.require(:associate).permit(:company_name, :title, :first_name, :last_name, :mobile_number, :landline_number, :bussiness_category, :address_building, :address_street, :address_landmark, :address_area, :address_city, :address_pincode, :contact_person, :contact_person_designation, :fax_number, :fax_number_two, :toll_free_number, :toll_free_number_two, :email_id, :website, :display_hours_status, :year_of_establishment, :annual_turnover, :number_of_employees, :professional_association, :certifications, :payment_mode_id, :monday_from, :monday_to, :monday_status, :tuesday_from, :tuesday_to, :tuesday_status, :wednesday_from, :wednesday_to, :wednesday_status, :thursday_from, :thursday_to, :thursday_status, :friday_from, :friday_to, :friday_status, :saturday_from, :saturday_to, :saturday_status, :sunday_from, :sunday_to, :sunday_status, :center_id)
    end
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/views/associates/_form.html.erb
<div class="container">
  <div class='row'>
  <div class="col-md-3" style='float:left;margin-top:2%'>
    <ul class="list-group">
       <li class="list-group-item"><a id='one' href='#'>Location Information</a></li>
       <li class="list-group-item">Contact Information</li>
       <li class="list-group-item">Other Information</li>
       <li class="list-group-item">Business Keywords</li>
       <li class="list-group-item">Add Keywords</li>
       <li class="list-group-item">View/Remove Keywords</li>
       <li class="list-group-item">Upload Video/Logo/Pictures</li>
    </ul>
 </div> 
 <div class="col-md-8" style='float:left;margin-left:60px;margin-top:1%'>
 <div class="form-area">  
   <%= simple_form_for(@associate) do |f| %>
     <%= f.error_notification %>
     <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


     <div class="form-inputs">
     <div class='display-area'>
     
     </div>

     <div class='two'>  
       <%= f.input :bussiness_category %>
       <%= f.input :address_building %>
       <%= f.input :address_street %>
       <%= f.input :address_landmark %>
       <%= f.input :address_area %>
       <%= f.input :address_city %>
       <%= f.input :address_pincode %>
     </div>
     <div class='three'>  
       <%= f.input :contact_person %>
       <%= f.input :contact_person_designation %>
       <%= f.input :fax_number %>
       <%= f.input :fax_number_two %>
       <%= f.input :toll_free_number %>
       <%= f.input :toll_free_number_two %>
     </div>
     <div class='four'>  
       <%= f.input :email_id %>
       <%= f.input :website %>
       <%= f.input :display_hours_status %>
       <%= f.input :year_of_establishment %>
       <%= f.input :annual_turnover %>
       <%= f.input :number_of_employees %>
     </div>
     <div class='five'>  
       <%= f.input :professional_association %>
       <%= f.input :certifications %>
       <%= f.association :payment_mode %>
       <%= f.input :monday_from %>
       <%= f.input :monday_to %>
       <%= f.input :monday_status %>
       <%= f.input :tuesday_from %>
       <%= f.input :tuesday_to %>
       <%= f.input :tuesday_status %>
       <%= f.input :wednesday_from %>
       <%= f.input :wednesday_to %>
       <%= f.input :wednesday_status %>
     </div>
     <div class='six'>  
       <%= f.input :thursday_from %>
       <%= f.input :thursday_to %>
       <%= f.input :thursday_status %>
       <%= f.input :friday_from %>
       <%= f.input :friday_to %>
       <%= f.input :friday_status %>
       <%= f.input :saturday_from %>
       <%= f.input :saturday_to %>
       <%= f.input :saturday_status %>
       <%= f.input :sunday_from %>
       <%= f.input :sunday_to %>
       <%= f.input :sunday_status %>
       <%= f.association :center %>
     </div>  
     </div>

     <div class="form-actions">
       <%= f.button :submit %>
     </div>
   <% end %>
<div>
  </div>
</div>      

<script>
$(document).ready(function(){
  $("#one").click(function(){
    alert();
  })
})
</script>

app/views/associates/_free_form.html.erb
<div class="container">
  <div class='row'>
  <div class="col-md-3" style='float:left;margin-top:2%'>
    <ul class="list-group">
       <li class="list-group-item"><a id='one' href='#'>Location Information</a></li>
       <li class="list-group-item"><a id='one' href='#two'>Contact Information</a></li>
    </ul>
 </div> 
 <div class="col-md-8" style='float:left;margin-left:60px;margin-top:1%'>
 <div class="form-area">  
   <%= simple_form_for(@associate) do |f| %>
     <%= f.error_notification %>
     <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

     <div class="form-inputs">
     <div class='display-area'>
     
     </div>

     <div class='two' id='two'>  
        <%= f.association :associate_category %>
        <%= f.input :address_building %>
       <%= f.input :address_street %>
       <%= f.input :address_landmark %>
       <%= f.input :address_area %>
       <%= f.input :address_city %>
       <%= f.input :address_pincode %>
     </div>
     <div class='three' id='three'>  
       <%= f.input :contact_person %>
       <%= f.input :contact_person_designation %>
       <%= f.input :fax_number %>
       <%= f.input :fax_number_two %>
       <%= f.input :toll_free_number %>
       <%= f.input :toll_free_number_two %>
     </div>
     <div class='four' id='four'>  
       <%= f.input :email_id %>
       <%= f.input :website %>
       <%= f.input :display_hours_status %>
       <%= f.input :year_of_establishment %>
       <%= f.input :annual_turnover %>
       <%= f.input :number_of_employees %>
     </div>
     <div class='six' id='six'>  
       <%= f.association :center %>
     </div>  
     </div>

     <div class="form-actions">
       <%= f.button :submit %>
     </div>
   <% end %>
<div>
  </div>
</div>      

<script>
$(document).ready(function(){
  $("#one").click(function(){
          
  })
})
</script>

app/views/associates/_paid_form.html.erb
<div class="container">
  <div class='row'>
  <div class="col-md-3" style='float:left;margin-top:2%'>
    <ul class="list-group">
       <li class="list-group-item"><a id='one' href='#'>Location Information</a></li>
       <li class="list-group-item"><a id='one' href='#two'>Contact Information</a></li>
       <li class="list-group-item"><a id='one' href='#three'>Other Information</a></li>
       <li class="list-group-item"><a id='one' href='#four'>Business Keywords</a></li>
       <li class="list-group-item"><a id='one' href='#five'>Add Keywords</a></li>
       <li class="list-group-item"><a id='one' href='#six'>View/Remove Keywords</a></li>
       <li class="list-group-item"><a id='one' href='#seven'>Upload Video/Logo/Pictures</a></li>
    </ul>
 </div> 
 <div class="col-md-8" style='float:left;margin-left:60px;margin-top:1%'>
 <div class="form-area">  
   <%= simple_form_for(@associate) do |f| %>
     <%= f.error_notification %>
     <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

     <div class="form-inputs">
     <div class='display-area'>
     
     </div>

     <div class='two' id='two'>  
       <%= f.association :volenter %>
       <%= f.association :associate_category %>
       <%= f.input :address_building %>
       <%= f.input :address_street %>
       <%= f.input :address_landmark %>
       <%= f.input :address_area %>
       <%= f.input :address_city %>
       <%= f.input :address_pincode %>
     </div>
     <div class='three' id='three'>  
       <%= f.input :contact_person %>
       <%= f.input :contact_person_designation %>
       <%= f.input :fax_number %>
       <%= f.input :fax_number_two %>
       <%= f.input :toll_free_number %>
       <%= f.input :toll_free_number_two %>
     </div>
     <div class='four' id='four'>  
       <%= f.input :email_id %>
       <%= f.input :website %>
       <%= f.input :display_hours_status %>
       <%= f.input :year_of_establishment %>
       <%= f.input :annual_turnover %>
       <%= f.input :number_of_employees %>
     </div>
     <div class='five' id='five'>  
       <%= f.input :professional_association %>
       <%= f.input :certifications %>
       <%= f.association :payment_mode %>
       <%= f.input :monday_from %>
       <%= f.input :monday_to %>
       <%= f.input :monday_status %>
       <%= f.input :tuesday_from %>
       <%= f.input :tuesday_to %>
       <%= f.input :tuesday_status %>
       <%= f.input :wednesday_from %>
       <%= f.input :wednesday_to %>
       <%= f.input :wednesday_status %>
     </div>
     <div class='six' id='six'>  
       <%= f.input :thursday_from %>
       <%= f.input :thursday_to %>
       <%= f.input :thursday_status %>
       <%= f.input :friday_from %>
       <%= f.input :friday_to %>
       <%= f.input :friday_status %>
       <%= f.input :saturday_from %>
       <%= f.input :saturday_to %>
       <%= f.input :saturday_status %>
       <%= f.input :sunday_from %>
       <%= f.input :sunday_to %>
       <%= f.input :sunday_status %>
       <%= f.association :center %>
       <%= f.association :associate_category %>
     </div>  
     </div>

     <div class="form-actions">
       <%= f.button :submit %>
     </div>
   <% end %>
<div>
  </div>
</div>      

<script>
$(document).ready(function(){
  $("#one").click(function(){
          
  })
})
</script>

app/views/associates/edit.html.erb
<h1>Editing Associate</h1>

<%= render 'form' %>

<%= link_to 'Show', @associate %> |
<%= link_to 'Back', associates_path %>

app/views/associates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Associates</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Title</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Mobile number</th>
      <th>Landline number</th>
      <th>Bussiness category</th>
      <th>Address building</th>
      <th>Address street</th>
      <th>Address landmark</th>
      <th>Address area</th>
      <th>Address city</th>
      <th>Address pincode</th>
      <th>Contact person</th>
      <th>Contact person designation</th>
      <th>Fax number</th>
      <th>Fax number two</th>
      <th>Toll free number</th>
      <th>Toll free number two</th>
      <th>Email</th>
      <th>Website</th>
      <th>Display hours status</th>
      <th>Year of establishment</th>
      <th>Annual turnover</th>
      <th>Number of employees</th>
      <th>Professional association</th>
      <th>Certifications</th>
      <th>Payment mode</th>
      <th>Monday from</th>
      <th>Monday to</th>
      <th>Monday status</th>
      <th>Tuesday from</th>
      <th>Tuesday to</th>
      <th>Tuesday status</th>
      <th>Wednesday from</th>
      <th>Wednesday to</th>
      <th>Wednesday status</th>
      <th>Thursday from</th>
      <th>Thursday to</th>
      <th>Thursday status</th>
      <th>Friday from</th>
      <th>Friday to</th>
      <th>Friday status</th>
      <th>Saturday from</th>
      <th>Saturday to</th>
      <th>Saturday status</th>
      <th>Sunday from</th>
      <th>Sunday to</th>
      <th>Sunday status</th>
      <th>Center</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @associates.each do |associate| %>
      <tr>
        <td><%= associate.company_name %></td>
        <td><%= associate.title %></td>
        <td><%= associate.first_name %></td>
        <td><%= associate.last_name %></td>
        <td><%= associate.mobile_number %></td>
        <td><%= associate.landline_number %></td>
        <td><%= associate.bussiness_category %></td>
        <td><%= associate.address_building %></td>
        <td><%= associate.address_street %></td>
        <td><%= associate.address_landmark %></td>
        <td><%= associate.address_area %></td>
        <td><%= associate.address_city %></td>
        <td><%= associate.address_pincode %></td>
        <td><%= associate.contact_person %></td>
        <td><%= associate.contact_person_designation %></td>
        <td><%= associate.fax_number %></td>
        <td><%= associate.fax_number_two %></td>
        <td><%= associate.toll_free_number %></td>
        <td><%= associate.toll_free_number_two %></td>
        <td><%= associate.email_id %></td>
        <td><%= associate.website %></td>
        <td><%= associate.display_hours_status %></td>
        <td><%= associate.year_of_establishment %></td>
        <td><%= associate.annual_turnover %></td>
        <td><%= associate.number_of_employees %></td>
        <td><%= associate.professional_association %></td>
        <td><%= associate.certifications %></td>
        <td><%= associate.payment_mode %></td>
        <td><%= associate.monday_from %></td>
        <td><%= associate.monday_to %></td>
        <td><%= associate.monday_status %></td>
        <td><%= associate.tuesday_from %></td>
        <td><%= associate.tuesday_to %></td>
        <td><%= associate.tuesday_status %></td>
        <td><%= associate.wednesday_from %></td>
        <td><%= associate.wednesday_to %></td>
        <td><%= associate.wednesday_status %></td>
        <td><%= associate.thursday_from %></td>
        <td><%= associate.thursday_to %></td>
        <td><%= associate.thursday_status %></td>
        <td><%= associate.friday_from %></td>
        <td><%= associate.friday_to %></td>
        <td><%= associate.friday_status %></td>
        <td><%= associate.saturday_from %></td>
        <td><%= associate.saturday_to %></td>
        <td><%= associate.saturday_status %></td>
        <td><%= associate.sunday_from %></td>
        <td><%= associate.sunday_to %></td>
        <td><%= associate.sunday_status %></td>
        <td><%= associate.center %></td>
        <td><%= link_to 'Show', associate %></td>
        <td><%= link_to 'Edit', edit_associate_path(associate) %></td>
        <td><%= link_to 'Destroy', associate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Associate', new_associate_path %>

app/views/associates/listing.html.erb
<%= render :partial => '/welcome/nav' %>

<div class="container" style='margin-top:50px'>
  <% if @response %>
    <% @response.errors.each do |key, message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>
<div class="col-md-8" style='float:left;margin-left:60px;margin-top:1%'>
 <h2> Bussiness Listing</h2><br>
<div class="form-area">  
  <%= simple_form_for(:associate, :url => new_associate_path,method: :get) do |f| %>
    <%= f.error_notification %>
    <div class='two' id='two'>  
      <div class="form-group">
         <%= label_tag "authy-countries", "Country code:" %>
         <div class ='form-control'>
         <%= select_tag "authy-countries", nil, name: 'country_code', 'data-show-as': 'number',required: true  %>
         </div>
      </div>
      <div>
        <%= label_tag "phone_number", "Phone number:" %>
        <%= telephone_field_tag "phone_number", nil, name: 'phone_number', class:'form-control'%>
       </div><br>
        <div>
            <%= label_tag "method", "Verification method:" %>
            <%= label_tag "method_sms", "SMS: "%>
            <%= radio_button_tag "method", "sms", class:"radio-inline"  %>
            <%= label_tag "method_call", "Call: " %>
            <%= radio_button_tag "method", "call",class:"radio-inline" %>
        </div><br>
            <%= f.input :company_name %>
            <%= f.input :title %>
            <%= f.input :first_name %>
            <%= f.input :last_name %>
            <%= f.input :mobile_number %>
            <%= f.input :landline_number %>
            <%= f.input :associate_type, collection: ['Paid','Free'],selected: 'Paid' %>
       </div>
    <div class="form-actions">
      <%= f.button :submit, 'Next' %>
    </div>
<% end %>
</div>    

app/views/associates/new.html.erb
<%= render :partial => '/welcome/nav' %>

<div class="container" style='margin-top:50px'>
<h1>New Associate</h1>

<% if @state == 'Paid'%>
   <%= render 'paid_form' %>
<% elsif @state == 'Free' %>
   <%= render 'free_form' %>
<% end %>

<%= link_to 'Back', associates_path %>

app/views/associates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @associate.company_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @associate.title %>
</p>

<p>
  <strong>First name:</strong>
  <%= @associate.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @associate.last_name %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @associate.mobile_number %>
</p>

<p>
  <strong>Landline number:</strong>
  <%= @associate.landline_number %>
</p>

<p>
  <strong>Bussiness category:</strong>
  <%= @associate.bussiness_category %>
</p>

<p>
  <strong>Address building:</strong>
  <%= @associate.address_building %>
</p>

<p>
  <strong>Address street:</strong>
  <%= @associate.address_street %>
</p>

<p>
  <strong>Address landmark:</strong>
  <%= @associate.address_landmark %>
</p>

<p>
  <strong>Address area:</strong>
  <%= @associate.address_area %>
</p>

<p>
  <strong>Address city:</strong>
  <%= @associate.address_city %>
</p>

<p>
  <strong>Address pincode:</strong>
  <%= @associate.address_pincode %>
</p>

<p>
  <strong>Contact person:</strong>
  <%= @associate.contact_person %>
</p>

<p>
  <strong>Contact person designation:</strong>
  <%= @associate.contact_person_designation %>
</p>

<p>
  <strong>Fax number:</strong>
  <%= @associate.fax_number %>
</p>

<p>
  <strong>Fax number two:</strong>
  <%= @associate.fax_number_two %>
</p>

<p>
  <strong>Toll free number:</strong>
  <%= @associate.toll_free_number %>
</p>

<p>
  <strong>Toll free number two:</strong>
  <%= @associate.toll_free_number_two %>
</p>

<p>
  <strong>Email:</strong>
  <%= @associate.email_id %>
</p>

<p>
  <strong>Website:</strong>
  <%= @associate.website %>
</p>

<p>
  <strong>Display hours status:</strong>
  <%= @associate.display_hours_status %>
</p>

<p>
  <strong>Year of establishment:</strong>
  <%= @associate.year_of_establishment %>
</p>

<p>
  <strong>Annual turnover:</strong>
  <%= @associate.annual_turnover %>
</p>

<p>
  <strong>Number of employees:</strong>
  <%= @associate.number_of_employees %>
</p>

<p>
  <strong>Professional association:</strong>
  <%= @associate.professional_association %>
</p>

<p>
  <strong>Certifications:</strong>
  <%= @associate.certifications %>
</p>

<p>
  <strong>Payment mode:</strong>
  <%= @associate.payment_mode %>
</p>

<p>
  <strong>Monday from:</strong>
  <%= @associate.monday_from %>
</p>

<p>
  <strong>Monday to:</strong>
  <%= @associate.monday_to %>
</p>

<p>
  <strong>Monday status:</strong>
  <%= @associate.monday_status %>
</p>

<p>
  <strong>Tuesday from:</strong>
  <%= @associate.tuesday_from %>
</p>

<p>
  <strong>Tuesday to:</strong>
  <%= @associate.tuesday_to %>
</p>

<p>
  <strong>Tuesday status:</strong>
  <%= @associate.tuesday_status %>
</p>

<p>
  <strong>Wednesday from:</strong>
  <%= @associate.wednesday_from %>
</p>

<p>
  <strong>Wednesday to:</strong>
  <%= @associate.wednesday_to %>
</p>

<p>
  <strong>Wednesday status:</strong>
  <%= @associate.wednesday_status %>
</p>

<p>
  <strong>Thursday from:</strong>
  <%= @associate.thursday_from %>
</p>

<p>
  <strong>Thursday to:</strong>
  <%= @associate.thursday_to %>
</p>

<p>
  <strong>Thursday status:</strong>
  <%= @associate.thursday_status %>
</p>

<p>
  <strong>Friday from:</strong>
  <%= @associate.friday_from %>
</p>

<p>
  <strong>Friday to:</strong>
  <%= @associate.friday_to %>
</p>

<p>
  <strong>Friday status:</strong>
  <%= @associate.friday_status %>
</p>

<p>
  <strong>Saturday from:</strong>
  <%= @associate.saturday_from %>
</p>

<p>
  <strong>Saturday to:</strong>
  <%= @associate.saturday_to %>
</p>

<p>
  <strong>Saturday status:</strong>
  <%= @associate.saturday_status %>
</p>

<p>
  <strong>Sunday from:</strong>
  <%= @associate.sunday_from %>
</p>

<p>
  <strong>Sunday to:</strong>
  <%= @associate.sunday_to %>
</p>

<p>
  <strong>Sunday status:</strong>
  <%= @associate.sunday_status %>
</p>

<p>
  <strong>Center:</strong>
  <%= @associate.center %>
</p>

<%= link_to 'Edit', edit_associate_path(@associate) %> |
<%= link_to 'Back', associates_path %>

app/views/associates/verify.html.erb
<%= render :partial => '/welcome/nav' %>

<div class="container" style='margin-top:50px'>
<% if @response %>
<% @response.errors.each do |key, message| %>
  <p><%= message %></p>
<% end %>
<% end %>
<div class="col-md-8" style='float:left;margin-left:60px;margin-top:1%'>
 <h2> Verify PhoneNumber</h2><br>
  <div class="form-area">  
 
    <%= form_tag(verification2_path, method: :post) do -%>

      <div >
        <%= text_field_tag :code, params[:code],placeholder:"Enter the code sent to your mobile number:", 
        autofocus: true, class: 'form-control search-box input-md' %>
      </div><br>
      <%= button_tag "Verify",class: 'btn btn-md btn-primary' %>

    <% end -%>
    
  </div>  
</div>     